### ISSUE TITLE
Access to Copilot

### ISSUE THREAD

**Issue by GT2856** [Netapp-Copilot/new-user#347]
### Netapp Username

tgokulna

**Comment by Netapp-audit** [comment]
Hi @GT2856, welcome back to Copilot!!!

**Comment by Netapp-audit** [comment]
Hi @GT2856, Your account has been reactivated. You should now have access to Copilot.

**Comment by GT2856** [comment]
2024-09-22 05:30:26.179 [error] [auth] auth: FetchError: read ECONNRESET
    at fetch (/u/tgokulna/.vscode-server/extensions/github.copilot-1.232.0/node_modules/@adobe/helix-fetch/src/fetch/index.js:99:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at cachingFetch (/u/tgokulna/.vscode-server/extensions/github.copilot-1.232.0/node_modules/@adobe/helix-fetch/src/fetch/index.js:288:16)
    at Hne.fetch (/u/tgokulna/.vscode-server/extensions/github.copilot-1.232.0/lib/src/network/helix.ts:93:22)
    at fetchCopilotToken (/u/tgokulna/.vscode-server/extensions/github.copilot-1.232.0/lib/src/auth/copilotToken.ts:196:16)
    at authFromGitHubToken (/u/tgokulna/.vscode-server/extensions/github.copilot-1.232.0/lib/src/auth/copilotToken.ts:129:22)
    at auth (/u/tgokulna/.vscode-server/extensions/github.copilot-1.232.0/extension/src/auth.ts:40:25)
    at authShowWarnings (/u/tgokulna/.vscode-server/extensions/github.copilot-1.232.0/extension/src/auth.ts:131:25)
    at yX.getCopilotToken (/u/tgokulna/.vscode-server/extensions/github.copilot-1.232.0/extension/src/auth.ts:174:33)
    at retryAuthentication (/u/tgokulna/.vscode-server/extensions/github.copilot-1.232.0/extension/src/auth.ts:93:9)
    at Mae.retryCTA (/u/tgokulna/.vscode-server/extensions/github.copilot-1.232.0/extension/src/auth.ts:121:24) {
  type: 'system',
  _name: 'FetchError',
  code: 'ECONNRESET',
  errno: -104,
  erroredSysCall: 'read'
}

getting this issue when try to login into gitHub coPilot.
Environment: BigTop using vsCode IDE and updates the extension to latest
